travis:
  secure:
    BINSTAR_TOKEN: iDsiZIaHgMA1lrnA7RmnrugKC5xgC6OYXaUd6KfmPl0Wcz90JRNkaVBY8Ol76i0i037INlb8hJPbBzaBy2ISbl5TSVeVX4GsnUyy838HsTw4zlAlWZzXtGVj36PRxBGfyqbF2tpDAh1gNc6hCW7xALlkI0ew6sp7lZ9ynGlEGoMAOL9sWuFtmCLkNr5Af59g+w5jhSzS04i1UCjOIltcvmrTrLobdF7zv+zFTU3YblMm8JV9/fvYCR4UjdTyUfy4MgU/4BMMZ3MmMLif7M10KE0047En8fG2/bd4aWb5wgaDCgE6hxAUI6fkaCnhDhBkqv6UMcjYj83MaxEb6qXa5bchu+QjJML/zoEq+nUUHRZ7i3J582Daeq9cLLvQbNLIDx4Z9QeXlQSPwBq92lcQbl2npqgPLdp8bSiJzZRoUc5ENbd45vTcjagKDsTG5PovsYqXwW+89n/ZVRAAecx89DK4OXpAylNOx+LlKglsZDpSixt/75fTnjhBef/yj0GSvxilkgMPD1tsI9ulgnxs/5x8km0Be+5AFOVBel6ehT9gqYc/pQLmfwNasP7+FHAGIvKd0a2rE4g93WNE9Aj3p5zp/bFurjFjR/QXDD0B5TjvFbw5biJHsUPmvG5qDioSkG51BmPbECsskS5bOuJzoQs6lLUd680uh5DE1pd+OmM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
