travis:
  secure:
    BINSTAR_TOKEN: mEqO4zeRglWykAJZYEEHPbBd3yV6aJWb6vtk0czo0THUo+lonR/Fymu/9cY7+t4iELMpCRxeV8CLjWF5VCWTtpLskpCHd6rDYqPL/8rcXEmBG0akW8ul/h1YWWJUQy1FaiCM0rAtxj6iFQEr+2XFfoVaZCgbB4c4x5w6tNrBwatvbWrF82at3JQazFbh39BjpFUBJ3JM4nZiMbmfRJbT2Z+GQ8quBHQhc6DwuOgmXEC097ISbQDyKckrayqpSBmwfmw4yeclDHU31bOYfzpGEz2VomkZ4J+lj21hgSVgh2latNxLEf6zAs7KQgBg7XyuspXThfERuo8lSCzUJQnIs+KnBSr43LJlFKpaiQZjlUt2lcKKLs5c4gPuqAlh6/NEREp+vG9x+lHE/6KkiWUAvgSWYPgbaE9dcveok2VgV9EZoeGqp6AzJn0GmFCtO4bICIO090yJTfFSFUJw6XXaV6g+ysC2EkL1mp5lA/5833VS4XSk4CwdDwHr7EXw4Pykt6scBDg1EZBjxiat/8ayZh8GyTUSmrl8G94xDmLbnH+PdEi2yYmH/YzecRsFyb5eODwjldGwMdR1ehb8Idnn19MMAoLd5fTauZP//uDKEKBUhmcf9YdMTYB4kBRprMbSxIGPe99G/+ZfdCAgygSnZA6v2YkZ4FdqpqaiKgASqoE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
